spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kyc_demo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis相關
  redis:
    host: localhost
    port: 6379
    password:
#    timeout: 500
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  mail:
    username: metalinksofficial@gmail.com
    password: yvurnakpvymydhet
    freemarker:
      cache: false
logging:
  level:
    root: INFO
    com:
      wanda: DEBUG
project:
  host-name: kyc.demo
env:
  platform:
    profile: local
    code: kyc_demo
    en-name: BistreetX_kyc_demo
    tw-name: BistreetX_kyc_demo
    cn-name: BistreetX_kyc_demo
  gcp.bucket: kyc-project-349915-image
  gcp.token: upload/gcp-bucket-dev.json
  gcp.image-url: https://kyc-backend.snailloop.com/bucket