package com.wanda.kyc.exception.enumeration;

import com.wanda.kyc.exception.IRuntimeExceptionEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;


@Getter
@AllArgsConstructor
public enum AppExceptionEnum implements IRuntimeExceptionEnum {

	//@off
//	CODE_ERROR("APP_0001", "CODE_ERROR", "驗證碼錯誤"),
	NFT_LOCK_ERROR("APP_0002", "NFT_LOCK_ERROR", "其他會員購買中"),
	NFT_STATUS_ERROR("APP_0003", "NFT_STATUS_ERROR", "商品狀態錯誤"),
	//	NFT_SELLING_TIME_ERROR("APP_0004", "NFT_SELLING_TIME_ERROR", "尚未開賣"),
//	NFT_CANNOT_BUY_ERROR("APP_0005", "NFT_CANNOT_BUY_ERROR", "無法購買商品"),
//	NFT_PAYMENT_ERROR("APP_0006", "NFT_PAYMENT_ERROR", "支付方式錯誤"),
//	NFT_ORDER_ROLE_ERROR("APP_0007", "NFT_ORDER_ROLE_ERROR", "商品訂單角色錯誤"),
//	NFT_ORDER_STATUS_ERROR("APP_0008", "NFT_ORDER_STATUS_ERROR", "商品訂單狀態錯誤"),
	NFT_ORDER_TAKER_ERROR("APP_0009", "NFT_ORDER_TAKER_ERROR", "不能購買自己賣的商品"),
	//	NFT_SPLIT_PRICE_ERROR("APP_0010", "NFT_SPLIT_PRICE_ERROR", "切分金額錯誤"),
//	FEE_ORDER_STATUS_ERROR("APP_0011", "FEE_ORDER_STATUS_ERROR", "手續費訂單狀態錯誤"),
//	AUTH_ERROR("APP_0012", "AUTH_ERROR", "權限錯誤"),
//	BALANCE_ERROR("APP_0013", "BALANCE_ERROR", "餘額不足"),
	NFT_NOT_FOUND_ERROR("APP_0014", "NFT_NOT_FOUND_ERROR", "查無商品"),
	//	MARKET_CONFIG_NOT_FOUND_ERROR("APP_0015", "MARKET_CONFIG_NOT_FOUND_ERROR", "查無市場設定"),
//	USER_APP_WALLET_NOT_FOUND_ERROR("APP_0016", "USER_APP_WALLET_NOT_FOUND_ERROR", "查無錢包"),
//	USER_APP_SYSTEM_ADDRESS_NOT_FOUND_ERROR("APP_0017", "USER_APP_SYSTEM_ADDRESS_NOT_FOUND_ERROR", "查無系統錢包地址"),
	USER_APP_NOT_FOUND_ERROR("APP_0018", "USER_APP_NOT_FOUND_ERROR", "查無會員"),
//	NFT_ORDER_NOT_FOUND_ERROR("APP_0019", "NFT_ORDER_NOT_FOUND_ERROR", "查無商品訂單"),
//	FEE_ORDER_NOT_FOUND_ERROR("APP_0020", "FEE_ORDER_NOT_FOUND_ERROR", "查無手續費訂單"),
//	MARKET_NOT_FOUND_ERROR("APP_0021", "MARKET_NOT_FOUND_ERROR", "查無市場"),
//	NFT_TRANSFER_COUNT_ERROR("APP_0022", "NFT_TRANSFER_COUNT_ERROR", "商品轉移次數錯誤"),
//	NFT_BUY_STATUS_ERROR("APP_0023", "NFT_BUY_STATUS_ERROR", "商品可購買狀態錯誤"),
//	PLATFORM_CONFIG_NOT_FOUND_ERROR("APP_0024", "PLATFORM_CONFIG_NOT_FOUND_ERROR", "查無平台設定"),
//	USER_APP_PAYMENT_NOT_FOUND_ERROR("APP_0025", "USER_APP_NOT_FOUND_ERROR", "查無支付設定"),
//	NFT_SPLIT_LOCK_ERROR("APP_0026", "NFT_SPLIT_LOCK_ERROR", "商品分割中"),
//	AGENT_AUTH_ERROR("APP_0027", "AGENT_AUTH_ERROR", "無代理權限"),
//	MARKET_APPLY_DUPLICATE_ERROR("APP_0028", "MARKET_APPLY_DUPLICATE_ERROR", "賣場申請重複"),
//	MARKET_NAME_DUPLICATE_ERROR("APP_0029", "MARKET_NAME_DUPLICATE_ERROR", "賣場名稱重複"),
//	USER_IS_NOT_LOWER("APP_0030", "USER_IS_NOT_LOWER", "會員非下線"),
//	BLACK_CONFIG_NOT_FOUND_ERROR("APP_0031", "BLACK_CONFIG_NOT_FOUND_ERROR", "查無黑名單設定"),
	;

	private String code;
	private String message;
	private String memo;

	//@on
}
